TIER1_FEATURES = [
    "telecom_ontime_rate",
    "telecom_ontime_trend",
    "telecom_plan_value",
    "telecom_active_months",
    "telecom_data_usage_gb",
    "telecom_missed_payments",
    "loc_address_changes_24m",
    "loc_years_at_current",
    "loc_is_metro",
    "loc_owns_home",
    "psych_engagement_score",
    "psych_consistency",
    "psych_completion_time_sec",
    "psych_straight_line_ratio",
    "psych_mean_answer",
    "psych_std_answer",
]

TIER2_FEATURES = [
    "bank_avg_monthly_inflow",
    "bank_inflow_trend",
    "bank_balance_volatility",
    "bank_payment_regularity",
    "bank_upi_txn_count",
    "bank_min_balance_ratio",
    "telecom_ontime_rate",
    "telecom_ontime_trend",
    "telecom_plan_value",
    "telecom_active_months",
    "telecom_data_usage_gb",
    "telecom_missed_payments",
    "ecom_purchase_frequency",
    "ecom_return_rate",
    "ecom_avg_monthly_spend",
    "ecom_spend_trend",
    "ecom_account_age_months",
    "ecom_category_diversity",
    "loc_address_changes_24m",
    "loc_years_at_current",
    "loc_is_metro",
    "loc_owns_home",
    "psych_engagement_score",
    "psych_consistency",
    "psych_completion_time_sec",
    "psych_straight_line_ratio",
    "psych_mean_answer",
    "psych_std_answer",
    "merchant_filing_regularity",
    "merchant_rating",
    "merchant_months_operating",
    "merchant_annual_turnover",
    "merchant_gst_returns_filed",
    "merchant_has_gst",
]

SCORE_BANDS = [
    (750, 850, "Excellent"),
    (650, 749, "Good"),
    (550, 649, "Fair"),
    (450, 549, "Poor"),
    (0, 449, "Not Eligible"),
]

LABEL_MAP = {"low": 0, "medium": 1, "high": 2}
